// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAsOCGMhfmxeBSkaYTEbcevx5NCZW_qT_w',
    appId: '1:822349363431:web:4191181bba16b3bbbfca42',
    messagingSenderId: '822349363431',
    projectId: 'flutt-listin',
    authDomain: 'flutt-listin.firebaseapp.com',
    storageBucket: 'flutt-listin.firebasestorage.app',
    measurementId: 'G-SD6WSQNCNP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDrGy1JgdAtxNZcpIzU7v7Uwx-2wiOaM-E',
    appId: '1:822349363431:android:596326e2e7b3986cbfca42',
    messagingSenderId: '822349363431',
    projectId: 'flutt-listin',
    storageBucket: 'flutt-listin.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAwVegpPmZfQ67ZfDwChMGR30ppkzhDMRk',
    appId: '1:822349363431:ios:12c7262b01a4009dbfca42',
    messagingSenderId: '822349363431',
    projectId: 'flutt-listin',
    storageBucket: 'flutt-listin.firebasestorage.app',
    iosBundleId: 'lima.ricarth.flutterFirebaseStorage',
  );
}
